### PR TITLE
Add metrics for document count and deleted document counts per database

### PR DESCRIPTION
**Pull request by pesimon**

### CODE REVIEW

**Comment by gesellix** [comment]
Thank you very much for your contribution!

The CI build failed, because the test doesn't expect the new metrics, yet. Can you please update the test cases at https://github.com/gesellix/couchdb-prometheus-exporter/blob/87675f899d0c8937d3527827e4205c988d7effac/couchdb-exporter_test.go#L133 and https://github.com/gesellix/couchdb-prometheus-exporter/blob/87675f899d0c8937d3527827e4205c988d7effac/couchdb-exporter_test.go#L137 to expect the increased number of metrics? See the test output for the changed values:

```
=== RUN   TestCouchdbStatsV1
--- FAIL: TestCouchdbStatsV1 (0.00s)
	couchdb-exporter_test.go:112: got more metrics (51) as expected (47)
=== RUN   TestCouchdbStatsV2
--- FAIL: TestCouchdbStatsV2 (0.01s)
	couchdb-exporter_test.go:112: got more metrics (84) as expected (80)
```

**Comment by pesimon** [comment]
Sure, will do.  Pretty cool test setup btw, as I actually did not verify that on couch v1

**Comment by gesellix** [comment]
Thanks a lot! :)

**Comment by gesellix** [comment]
The metrics will be available with Docker image `gesellix/couchdb-prometheus-exporter:17` (see https://hub.docker.com/r/gesellix/couchdb-prometheus-exporter/builds/ for build progress).

**Pull request merged**
