### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by gesellix**
Beware before merging: there's an issue in urfave/cli 1.21.0: https://github.com/urfave/cli/issues/850

### CODE REVIEW

**Comment by gesellix** [comment]
Build log:

```
# github.com/gesellix/couchdb-prometheus-exporter/fileutil
fileutil/properties_file_loader.go:69:25: cannot use MapInputSource literal (type *MapInputSource) as type altsrc.InputSourceContext in return argument:
	*MapInputSource does not implement altsrc.InputSourceContext (wrong type for Generic method)
		have Generic(string) ("github.com/gesellix/couchdb-prometheus-exporter/vendor/gopkg.in/urfave/cli.v1".Generic, error)
		want Generic(string) ("github.com/gesellix/couchdb-prometheus-exporter/vendor/github.com/urfave/cli".Generic, error)
```

**Comment by lynncyrin** [comment]
I'm pretty this error message ...

```
# github.com/gesellix/couchdb-prometheus-exporter/fileutil
fileutil/properties_file_loader.go:69:25: cannot use MapInputSource literal (type *MapInputSource) as type altsrc.InputSourceContext in return argument:
	*MapInputSource does not implement altsrc.InputSourceContext (wrong type for Generic method)
		have Generic(string) ("github.com/gesellix/couchdb-prometheus-exporter/vendor/gopkg.in/urfave/cli.v1".Generic, error)
		want Generic(string) ("github.com/gesellix/couchdb-prometheus-exporter/vendor/github.com/urfave/cli".Generic, error)
```

... is caused by this bit here

```diff
-have Generic(string) (".../vendor/gopkg.in/urfave/cli.v1".Generic, error)
+want Generic(string) (".../vendor/github.com/urfave/cli".Generic, error)
```

Find and replace `gopkg.in/urfave` with `github.com/urfave` and see if that works?

**Comment by gesellix** [comment]
Hey @lynncyrin, thanks for that official support by a maintainer :)
Your hint seems to be the fix, thanks a lot!

**Comment by gesellix** [comment]
Hm. Now the Docker build fails, but this seems to be unrelated:

```
--- FAIL: TestSemaphore (0.02s)
couchdb-client_test.go:30: Workers did not complete in time
FAIL
FAIL	github.com/gesellix/couchdb-prometheus-exporter/lib	0.288s
```

**Pull request merged**
