### PR TITLE
V2 metrics

### PR DESCRIPTION
**Pull request by kobuskc**
Hello,

I needed to add more metrics to use at work. This is the result of the changes I made. I also updated the tests to include the number of new metrics and requests.

Build output:

++ pwd
+ CWD=/Users/kobusc/work/builds/couchdb-prometheus-exporter
+ export SOURCE=/Users/kobusc/clones/couchdb-prometheus-exporter
+ SOURCE=/Users/kobusc/clones/couchdb-prometheus-exporter
+ export GOPATH=/Users/kobusc/work/builds/couchdb-prometheus-exporter/go
+ GOPATH=/Users/kobusc/work/builds/couchdb-prometheus-exporter/go
+ export APPPATH=/Users/kobusc/work/builds/couchdb-prometheus-exporter/go/src/github.com/gesellix/couchdb-prometheus-exporter
+ APPPATH=/Users/kobusc/work/builds/couchdb-prometheus-exporter/go/src/github.com/gesellix/couchdb-prometheus-exporter
+ mkdir -p /Users/kobusc/work/builds/couchdb-prometheus-exporter/go/src/github.com/gesellix/couchdb-prometheus-exporter
+ cp -r /Users/kobusc/clones/couchdb-prometheus-exporter/CODE_OF_CONDUCT.md /Users/kobusc/clones/couchdb-prometheus-exporter/Dockerfile /Users/kobusc/clones/couchdb-prometheus-exporter/Gopkg.lock /Users/kobusc/clones/couchdb-prometheus-exporter/Gopkg.toml /Users/kobusc/clones/couchdb-prometheus-exporter/LICENSE /Users/kobusc/clones/couchdb-prometheus-exporter/README.md /Users/kobusc/clones/couchdb-prometheus-exporter/cli /Users/kobusc/clones/couchdb-prometheus-exporter/couchdb-exporter.go /Users/kobusc/clones/couchdb-prometheus-exporter/couchdb-exporter_test.go /Users/kobusc/clones/couchdb-prometheus-exporter/examples /Users/kobusc/clones/couchdb-prometheus-exporter/glogadapt /Users/kobusc/clones/couchdb-prometheus-exporter/integrationtest-setup.sh /Users/kobusc/clones/couchdb-prometheus-exporter/integrationtest-teardown.sh /Users/kobusc/clones/couchdb-prometheus-exporter/lib /Users/kobusc/clones/couchdb-prometheus-exporter/munin /Users/kobusc/clones/couchdb-prometheus-exporter/testdata /Users/kobusc/clones/couchdb-prometheus-exporter/testutil /Users/kobusc/clones/couchdb-prometheus-exporter/vendor /Users/kobusc/work/builds/couchdb-prometheus-exporter/go/src/github.com/gesellix/couchdb-prometheus-exporter/.
+ cd /Users/kobusc/work/builds/couchdb-prometheus-exporter/go/src/github.com/gesellix/couchdb-prometheus-exporter
+ go get -d
+ go get -u github.com/golang/dep/cmd/dep
+ /Users/kobusc/work/builds/couchdb-prometheus-exporter/go/bin/dep ensure
+ go test -short
PASS
ok  	github.com/gesellix/couchdb-prometheus-exporter	0.048s
+ go build -a -ldflags '-s -w -extldflags "-static"' -o ./bin/couchdb-prometheus-exporter

### CODE REVIEW

**Comment by gesellix** [comment]
Hey, thanks a lot for your comprehensive contribution! As far as I can tell, everything looks great.

Though I'm going to merge I'd be interested whether you're already using the changes in production and whether the increased (doubled :) ) response payload has any relevant impact on the system's performance - same question regarding the requests to `.../_system`.

**Comment by gesellix** [comment]
The new metrics are available with release 23, also available as Docker image with the same tag.

**Comment by kobuskc** [comment]
> Hey, thanks a lot for your comprehensive contribution! As far as I can tell, everything looks great.
> 
> Though I'm going to merge I'd be interested whether you're already using the changes in production and whether the increased (doubled :) ) response payload has any relevant impact on the system's performance - same question regarding the requests to `.../_system`.

Thanks. I'm have been running this in dev and will deploy in production this week. I had similar concerns, so to test I replayed production requests on the same data in dev. So far I have not seen any relevant impact.

I'm happy to keep an eye on it for a few weeks and report back if I come across anything significant.

**Comment by gesellix** [comment]
> report back if I come across anything significant

**Pull request merged**
