### PR TITLE
Readme and Grafana panel

### PR DESCRIPTION
**Pull request by Poil**
I add an "instance" label because my node_name is "couchdb@127.0.0.1" on all my instances
also add a dashboard

### CODE REVIEW

**Comment by gesellix** [comment]
Note to self: relates to #36

**Comment by gesellix** [comment]
@Poil thanks a lot for your pull request!

You might have noticed that I have already been thinking about a default Grafana dashboard to be provided as an example (#36). Your dashboard looks great so far and would be a good match. I would like to create a more comprehensive example setup, though. I would like to add the necessary elements first and would prefer to let you add your dashboard on top of it. Would that work for you?

**Comment by Poil** [comment]
Hey,

No problem, I use your exporter, so I share my current dashboard, feel free to use, modify or not :)

**Comment by gesellix** [comment]
Thanks @Poil, I opted for taking your dashboard and adding it via #52 - along with some minor adjustments :)

**Pull request closed without merging**
